### ISSUE TITLE
PPO with num-processes = 1

### ISSUE THREAD

**Issue by bbalaji-ucsd** [ikostrikov/pytorch-a2c-ppo-acktr#124]
When I try to run PPO + CartPole with num-processes 1, I get the following error:

Command: python main.py --env-name "CartPole-v1" --algo ppo —num-processes 1 --no-vis

Traceback (most recent call last):
File "main.py", line 207, in <module>
main()
File "main.py", line 86, in main
obs = envs.reset()
File "pytorch-a2c-ppo-acktr/envs.py", line 122, in reset
obs = self.venv.reset()
File "/anaconda3/lib/python3.6/site-packages/baselines/common/vec_env/vec_normalize.py", line 47, in reset
return self._obfilt(obs)
File "/anaconda3/lib/python3.6/site-packages/baselines/common/vec_env/vec_normalize.py", line 36, in _obfilt
self.ob_rms.update(obs)
File "/anaconda3/lib/python3.6/site-packages/baselines/common/running_mean_std.py", line 12, in update
batch_count = x.shape[0]
AttributeError: 'list' object has no attribute 'shape'

**Comment by bbalaji-ucsd** [comment]
Yes, I git cloned yesterday from the master branch. 

It also doesn't work with num-processes 2 btw. Gives the following error:
Traceback (most recent call last):
  File "main.py", line 207, in <module>
    main()
  File "main.py", line 120, in main
    value_loss, action_loss, dist_entropy = agent.update(rollouts)
  File "/Users/bhabalaj/Repositories/Silverstone/pytorch-a2c-ppo-acktr/algo/ppo.py", line 49, in update
    for sample in data_generator:
  File "/Users/bhabalaj/Repositories/Silverstone/pytorch-a2c-ppo-acktr/storage.py", line 77, in feed_forward_generator
    "".format(num_processes, num_steps, num_processes * num_steps, num_mini_batch))
AssertionError: PPO requires the number of processes (2) * number of steps (5) = 10 to be greater than or equal to the number of PPO mini batches (32).

**Comment by ikostrikov** [comment]
Try to use default parameters for ppo (use the ones for mujoco).

**Comment by bbalaji-ucsd** [comment]
I don't have a MuJoCo license to verify (30 day license expired). I tried to replace "Reacher-v2" with "CartPole-v1" and that failed with the same error as above.

**Comment by ikostrikov** [comment]
Do you run it this way?

python main.py --env-name "CartPole-v1" --algo ppo --use-gae --vis-interval 1  --log-interval 1 --
num-steps 2048 --num-processes 1 --lr 3e-4 --entropy-coef 0 --value-loss-coef 1 --ppo-epoch 10 --num-mini-batch 32 --gamma 0.99 --tau 0.95 --num-frames 1000000

**Comment by bbalaji-ucsd** [comment]
Yes.

I also am not able to run Visdom due to some connection error. So I use no-vis option for now. But I get this error with or without no-vis

**Comment by HareshKarnan** [comment]
did anyone encounter this problem and solve it ?
