### ISSUE TITLE
Error when using box2D environment CarRacing-v0 

### ISSUE THREAD

**Issue by fenjiro** [ikostrikov/pytorch-a2c-ppo-acktr#145]
Hello every body,
with ATARI games the code work very well, but when, i tried to train CarRacing-v0  game (box2D environment), i get the error below. please, i need some help.

**python main.py --env-name "CarRacing-v0"**

Track generation: 1056..1324 -> 268-tiles track
Track generation: 1162..1460 -> 298-tiles track
Track generation: 1112..1400 -> 288-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1321..1655 -> 334-tiles track
Track generation: 1108..1389 -> 281-tiles track
Traceback (most recent call last):
  File "main.py", line 205, in <module>
    main()
  File "main.py", line 100, in main
    rollouts.masks[step])
  File "/home/osboxes/Downloads/pytorch-a2c-ppo-acktr-master/model.py", line 49, in act
    **value, actor_features, rnn_hxs = self.base(inputs, rnn_hxs, masks)**
  File "/home/osboxes/anaconda3/envs/AI35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/osboxes/Downloads/pytorch-a2c-ppo-acktr-master/model.py", line 163, in forward
    x = self.main(inputs / 255.0)
  File "/home/osboxes/anaconda3/envs/AI35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/osboxes/anaconda3/envs/AI35/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/osboxes/anaconda3/envs/AI35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/osboxes/anaconda3/envs/AI35/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/osboxes/anaconda3/envs/AI35/lib/python3.5/site-packages/torch/nn/functional.py", line 1024, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [16 x 2048], m2: [1568 x 512] at /opt/conda/conda-bld/pytorch_1532499195775/work/aten/src/TH/generic/THTensorMath.cpp:2070

**Comment by ikostrikov** [comment]
https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/commit/790c90e32fb656c6f774d1947210beeb5d429325

For the moment, this repository doesn't support envs with pixels inputs different from atari.

See the wrap_deepmind function. You need to implement similar preprocessing.
