### ISSUE TITLE
broken master (input shape)

### ISSUE THREAD

**Issue by CarloLucibello** [ikostrikov/pytorch-a2c-ppo-acktr#36]
It appears that last commit messed with input shape in Atari enviroment:
```python
[lucibello@bidsa-sc pytorch-a2c-ppo-acktr]$ python main.py 
#######
WARNING: All rewards are clipped or normalized so you need to use a monitor (see envs.py) or visdom plot to get true rewards
#######
Traceback (most recent call last):
  File "main.py", line 265, in <module>
    main()
  File "main.py", line 122, in main
    Variable(rollouts.masks[step], volatile=True))
  File "/home/lucibello/Git/pytorch-a2c-ppo-acktr/model.py", line 24, in act
    value, x, states = self(inputs, states, masks)
  File "/home/lucibello/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lucibello/Git/pytorch-a2c-ppo-acktr/model.py", line 87, in forward
    x = self.conv1(inputs / 255.0)
  File "/home/lucibello/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lucibello/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
  File "/home/lucibello/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 52, in conv2d
    return f(input, weight, bias)
RuntimeError: Given input size: (336, 84, 1). Calculated output size: (16, 20, 0). Output size is too small.
```
Reverting to recent commits fixes the problem.

Cheers
C

**Comment by ikostrikov** [comment]
Thanks for reporting the bug!

Fixed in https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/commit/c8a13eee13afdbd1323144e3be25f47c20f33546
