### ISSUE TITLE
DataParallel problem with PPO

### ISSUE THREAD

**Issue by AjayTalati** [ikostrikov/pytorch-a2c-ppo-acktr#4]
Hi, 

adding `act` breaks PPO?

```
Traceback (most recent call last):
  File "main.py", line 224, in <module>
    main()
  File "main.py", line 102, in main
    value, action, action_log_probs = actor_critic.act(Variable(rollouts.states[step], volatile=True))
  File "/home/ajay/anaconda3/envs/py35_pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 262, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'act'
```

I think the problem is here?

```

    actor_critic = ActorCritic(envs.observation_space.shape[0] * args.num_stack, envs.action_space)
    if args.algo == 'ppo':
        actor_critic = nn.DataParallel(actor_critic)
```

Tried the obvious fix, but got another error?

```
    value, action, action_log_probs = nn.DataParallel(actor_critic.act(Variable(rollouts.states[step], volatile=True)))                        
  File "/home/ajay/anaconda3/envs/py35_pytorch/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 53, in __init__
    self.module.cuda(device_ids[0])
AttributeError: 'tuple' object has no attribute 'cuda'
```

Tried without  `nn.DataParallel` and got another error?

```
Traceback (most recent call last):
  File "main.py", line 225, in <module>
    main()
  File "main.py", line 182, in main
    states_batch = rollouts.states[:-1].view(-1, *rollouts.states.size()[-3:])[indices]
TypeError: indexing a tensor with an object of type list. The only supported types are integers, slices, numpy scalars and torch.LongTensor or torch.ByteTensor as the only argument.
```

**Comment by ikostrikov** [comment]
Hi,

Try to update PyTorch, I'm using a self-compiled version.

I'm going to remove DataParallel in the next commit anyway.

**Comment by AjayTalati** [comment]
OK - everything works fine for `A2C`

Perhaps, add that user needs the OpenAI `Baselines` folder from this [repo](https://github.com/openai/baselines) in their directory?

**Comment by AjayTalati** [comment]
Unfortunately updating PyTorch doesn't fix this in my case? Still get,

```
(py35_pytorch) ajay@ajay-h8-1170uk:~/PythonProjects/pytorch-a2c-ppo-acktr-master$ python main.py --env-name "PongNoFrameskip-v4" --algo ppo --use-gae --num-processes 6 --num-steps 256 --vis-interval 1 --log-interval 1

#######
WARNING: All rewards are clipped so you need to use a monitor (see envs.py) or visdom plot to get true rewards
#######
[2017-09-23 01:25:09,165] Making new env: PongNoFrameskip-v4
[2017-09-23 01:25:09,169] Making new env: PongNoFrameskip-v4
[2017-09-23 01:25:09,172] Making new env: PongNoFrameskip-v4
[2017-09-23 01:25:09,180] Making new env: PongNoFrameskip-v4
[2017-09-23 01:25:09,185] Making new env: PongNoFrameskip-v4
[2017-09-23 01:25:09,188] Making new env: PongNoFrameskip-v4
Traceback (most recent call last):
  File "main.py", line 225, in <module>
    main()
  File "main.py", line 182, in main
    states_batch = rollouts.states[:-1].view(-1, *rollouts.states.size()[-3:])[indices]
TypeError: indexing a tensor with an object of type list. The only supported types are integers, slices, numpy scalars and torch.LongTensor or torch.ByteTensor as the only argument.
```

**Comment by ikostrikov** [comment]
What is the version of PyTorch that you are using?

**Comment by AjayTalati** [comment]
The latest one,

```
(py35_pytorch) ajay@ajay-h8-1170uk:~/PythonProjects/pytorch-a2c-ppo-acktr-master$ python
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
0.2.0_4
```

**Comment by ikostrikov** [comment]
You need to compile from sources to get the latest one. But I will fix it in the next commit.

**Comment by AjayTalati** [comment]
OK - thanks a lot, I'll try to compile from source tomorrow :+1: 

Are you interested in this, [Uncertainty Bellman Equation and Exploration](https://arxiv.org/pdf/1709.05380v1.pdf), seems quite impressive with SOTA on Montezuma's Revenge
